// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fssxyngwispxtvucoeyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzc3h5bmd3aXNweHR2dWNvZXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjQwOTAsImV4cCI6MjA1OTY0MDA5MH0.BMDVkwkZtqPln8YjltAUOFG730Xecpc-vXayqzTOjoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);